### ISSUE TITLE
"File already exist" warning and duplicate files being created

### ISSUE THREAD

**Issue by fullofcaffeine** [explorigin/modular-js#5]
Hey there Timothy!

Thanks for this lib, it's a great example on how to modify the js output, quite neat! Works fine for the most part.... but:

I'm having an issue. Whenever I compile the first time (when the module js don't exit) it works fine. If I make any changes to any of the module classes and compile again, I get this:

```
Warning : File already exists at /Users/fullofcaffeine/workspace/code/modular-js-haxe-test/bin/Module1.js. Saving to /Users/fullofcaffeine/workspace/code/modular-js-haxe-test/bin/Module1.js.1459556590.
Warning : File already exists at /Users/fullofcaffeine/workspace/code/modular-js-haxe-test/bin/Main.js. Saving to /Users/fullofcaffeine/workspace/code/modular-js-haxe-test/bin/Main.js.1459556590.
Warning : File already exists at /Users/fullofcaffeine/workspace/code/modular-js-haxe-test/bin/Module1.js. Saving to /Users/fullofcaffeine/workspace/code/modular-js-haxe-test/bin/Module1.js.1459556590.
Warning : File already exists at /Users/fullofcaffeine/workspace/code/modular-js-haxe-test/bin/Main.js. Saving to /Users/fullofcaffeine/workspace/code/modular-js-haxe-test/bin/Main.js.1459556590.
```

Do you know why this happens?

The sample project/sandbox is available here: https://github.com/fullofcaffeine/modualr-haxe-js-test

(PS: I'm looking into exteding/modifying this to support Ember 2 through Ember-CLI)

Thanks in advance!

**Comment by explorigin** [comment]
Yes, I was having a problem with multiple builds using the same files and trying to get it to work with some sort of DCE.  I was also using it as a tool to compare output and builds.

It happens [here](https://github.com/explorigin/modular-js/blob/master/src/modular/js/JsGenerator.hx#L154).  Feel free to fork and modify.  I'm taking a break from the Haxe community as I have more important things going on right now.

TBH, I'm tracking [Sweet.JS](https://github.com/mozilla/sweet.js).  When the next release lands, there will be almost zero reason to use Haxe anymore since Javascript will have all of:
- strong type-checking (Typescript)
- advanced macros (Sweet.JS)
- advanced constructs (ES6+)
- DCE (Webpack and/or Rollup)
- a better community (the Haxe leadership is stuck in game-dev world)

**Comment by fullofcaffeine** [comment]
Hi Timothy,

Thanks for pointing me out to the right direction. So, as far I as understand, that was a kind of debug code that you added there? 

Regarding `Sweet.JS`, ti does look very interesting, thanks for sharing!

And about Haxe I'd give it another chance. The community is (slowly) getting bigger and better, and while the ratio of people doing web is small, there's still some interesting stuff happening, besides personally I prefer Haxe to Typescript, as a language and toolkit.

Yeah, I agree that the path of least resistance (in case of TypeScript, being a superset of JS) is effective (also because the community is bigger and can tap into other communities more easily), and right now I'm not using Haxe for my most of main projects -- I still use ES6 + Ruby on the backend most of the time -- However, I do think investing time into Haxe could pay off in the long run, though.

You have contributed a lot of great stuff to the community and it'd be sad to see you go!

**Comment by explorigin** [comment]
> Thanks for pointing me out to the right direction. So, as far I as understand, that was a kind of debug code that you added there? 

Yep.  Feel free to comment out that section.  I don't have Haxe installed on my current machine, or I'd do it quickly.  Otherwise give me a few days and I'll get to it.

> And about Haxe I'd give it another chance.

I haven't written it off completely.  I do like Haxe as a language better than Typescript.  I have some projects in the pipeline right now that might use Haxe in the future, but for now they are all Javascript.

**Comment by fullofcaffeine** [comment]
> Yep. Feel free to comment out that section. I don't have Haxe installed on my current machine, or I'd do >it quickly. Otherwise give me a few days and I'll get to it.

Cool, will do it.

> I haven't written it off completely. I do like Haxe as a language better than Typescript. I have some >projects in the pipeline right now that might use Haxe in the future, but for now they are all Javascript.

Good to know! Excited to see what you come up with. By the way, thanks for taking the time to share your perspective on Haxe, and what Sweet.JS is all about.
